import { useMemo } from 'react';
import { useTwin } from '../store/twinStore';
import { TimeSeriesChart, SERIES } from '../components/operations/TimeSeriesChart';
import { PageTitle, Panel, Prov, Stat, StatStrip } from '../components/common/ui';
import { SAFETY_LIMITS } from '../services/modelConfig';
import { loadColor } from '../lib/format';
import { WellSelect } from '../components/layout/MainNav';

function ChartPanel({ title, unit, children, prov = 'SIMULATED' }: { title: string; unit: string; children: React.ReactNode; prov?: 'SIMULATED' | 'PREDICTED' }) {
  return (
    <Panel
      title={
        <span>
          {title} <span className="font-normal tracking-normal text-ink-3 normal-case">({unit})</span>
        </span>
      }
      right={<Prov kind={prov} />}
      bodyClass="px-1 pt-1"
    >
      {children}
    </Panel>
  );
}

export default function OperationsPage() {
  const trend = useTwin((s) => s.trend);
  const c = useTwin((s) => s.computed);
  const wellId = useTwin((s) => s.wellId);
  const data = useMemo(
    () =>
      trend.map((t) => ({
        time: t.time,
        oil: t.oil,
        liquid: t.liquid,
        wc: t.waterCut,
        temp: t.temperature,
        pip: t.pip,
        whp: t.whp,
        visc: t.viscosity,
        spm: t.spm,
        vfd: t.vfd,
        load: t.rodLoad,
        loadPred: t.rodLoadPred,
        torque: t.torque,
        eff: t.pumpEfficiency,
        fill: t.pumpFillage,
      })),
    [trend],
  );
  const onset = trend.find((t) => t.tH >= 0 && t.tH < 0.3 && trend.some((u) => u.tH > 0.5));
  const markers = onset ? [{ x: onset.time, label: 'cooling onset' }] : [];
  const x = c.sample;

  return (
    <div className="p-4">
      <PageTitle
        title={`Live operations dashboard — ${wellId}`}
        right={<WellSelect />}
        sub={
          <>
            Previous 24 h + live scenario samples · all series are <Prov kind="SIMULATED" /> observations generated by coupled models (not independent random values)
          </>
        }
      />
      <StatStrip cols={8}>
        <Stat label="Oil rate" value={x.oil.toFixed(1)} unit="BOPD" />
        <Stat label="Liquid" value={x.liquid.toFixed(1)} unit="BFPD" sub={`WC ${x.waterCut.toFixed(0)}%`} />
        <Stat label="Temperature" value={x.temperature.toFixed(1)} unit="°C" sub={c.thermalState} />
        <Stat label="Viscosity" value={x.viscosity.toFixed(0)} unit="cP" />
        <Stat label="SPM / VFD" value={x.spm.toFixed(1)} unit="spm" sub={`${x.vfd.toFixed(0)} Hz · stroke ${x.stroke.toFixed(1)} m`} />
        <Stat label="Rod load" value={<span style={{ color: loadColor(x.rodLoad) }}>{x.rodLoad.toFixed(0)}</span>} unit="%" sub={`+24 h: ${c.forecast.rodLoadCurrentSpm.value.toFixed(0)}%`} />
        <Stat label="Torque" value={x.torque.toFixed(1)} unit="kN·m" />
        <Stat label="Pump eff. / fill" value={x.pumpEfficiency.toFixed(0)} unit="%" sub={`fillage ${x.pumpFillage.toFixed(0)}%`} />
      </StatStrip>

      <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-2 2xl:grid-cols-3">
        <ChartPanel title="Production rate" unit="bbl/d">
          <TimeSeriesChart data={data} unit="bbl/d" markers={markers} series={[{ key: 'oil', name: 'Oil (BOPD)', color: SERIES.s1 }, { key: 'liquid', name: 'Liquid (BFPD)', color: SERIES.s2 }]} />
        </ChartPanel>
        <ChartPanel title="Temperature at pump intake" unit="°C">
          <TimeSeriesChart data={data} unit="°C" markers={markers} series={[{ key: 'temp', name: 'Temperature', color: SERIES.s1 }]} />
        </ChartPanel>
        <ChartPanel title="Oil viscosity" unit="cP">
          <TimeSeriesChart data={data} unit="cP" decimals={0} markers={markers} series={[{ key: 'visc', name: 'Viscosity', color: SERIES.s1 }]} />
        </ChartPanel>
        <ChartPanel title="Rod load (PPRL)" unit="% of rating">
          <TimeSeriesChart
            data={data}
            unit="%"
            markers={markers}
            domain={[60, 95]}
            refLines={[{ y: SAFETY_LIMITS.maxRodLoad, label: 'limit 90%', color: '#b3261e' }, { y: 80, label: 'HIGH band 80%', color: '#b7791f' }]}
            series={[
              { key: 'load', name: 'Observed (sim.)', color: SERIES.s1 },
              { key: 'loadPred', name: 'Forecast +24 h', color: SERIES.s2, dashed: true },
            ]}
          />
        </ChartPanel>
        <ChartPanel title="Pumping speed" unit="strokes/min">
          <TimeSeriesChart data={data} unit="spm" markers={markers} domain={[4, 12]} series={[{ key: 'spm', name: 'SPM', color: SERIES.s1 }]} />
        </ChartPanel>
        <ChartPanel title="VFD frequency" unit="Hz">
          <TimeSeriesChart data={data} unit="Hz" decimals={0} markers={markers} domain={[25, 50]} series={[{ key: 'vfd', name: 'VFD', color: SERIES.s1 }]} />
        </ChartPanel>
        <ChartPanel title="Peak gearbox torque" unit="kN·m">
          <TimeSeriesChart data={data} unit="kN·m" markers={markers} refLines={[{ y: SAFETY_LIMITS.maxTorque, label: 'rating 40', color: '#b3261e' }]} domain={[15, 45]} series={[{ key: 'torque', name: 'Torque', color: SERIES.s1 }]} />
        </ChartPanel>
        <ChartPanel title="Pump efficiency & fillage" unit="%">
          <TimeSeriesChart data={data} unit="%" decimals={0} markers={markers} domain={[50, 100]} series={[{ key: 'eff', name: 'Efficiency', color: SERIES.s1 }, { key: 'fill', name: 'Fillage', color: SERIES.s2 }]} />
        </ChartPanel>
        <ChartPanel title="Pressures" unit="bar">
          <TimeSeriesChart data={data} unit="bar" markers={markers} domain={[0, 14]} series={[{ key: 'pip', name: 'Pump intake', color: SERIES.s1 }, { key: 'whp', name: 'Wellhead', color: SERIES.s2 }]} />
        </ChartPanel>
        <ChartPanel title="Water cut" unit="%">
          <TimeSeriesChart data={data} unit="%" decimals={0} domain={[0, 100]} series={[{ key: 'wc', name: 'Water cut', color: SERIES.s1 }]} />
        </ChartPanel>
      </div>
      <div className="mt-3 text-[11px] text-ink-3">
        Coupling: temperature ↓ → viscosity ↑ (μ = A·exp(B/T)) → rod load ↑ and fillage ↓; SPM ↓ → rod load ↓ and fillage ↑. Stroke length constant at {x.stroke.toFixed(1)} m.
      </div>
    </div>
  );
}
