import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { useTwin } from '../store/twinStore';
import { BeforeAfter } from '../components/outcome/BeforeAfter';
import { PredictionValidation } from '../components/outcome/PredictionValidation';
import { Badge, Note, PageTitle, Panel, Prov, Stat, StatStrip } from '../components/common/ui';
import { TimeSeriesChart, SERIES } from '../components/operations/TimeSeriesChart';
import { SAFETY_LIMITS } from '../services/modelConfig';
import { evaluateSrp } from '../services/srpModel';

export default function OutcomePage() {
  const wellId = useTwin((s) => s.wellId);
  const o = useTwin((s) => s.outcome);
  const status = useTwin((s) => s.scenario.status);
  const decision = useTwin((s) => s.scenario.decision);
  const decidedBy = useTwin((s) => s.scenario.decidedBy);
  const trend = useTwin((s) => s.trend);
  const snap = useTwin((s) => s.decisionSnapshot);
  const cal = useTwin((s) => s.cal);
  const stroke = useTwin((s) => s.stroke);
  const eBefore = o ? evaluateSrp(cal, { spm: o.before.spm, stroke, viscosity: o.before.viscosity }, 'plant').kwhPerBbl : 0;
  const eAfter = o ? evaluateSrp(cal, { spm: o.observedAfter.spm, stroke, viscosity: o.observedAfter.viscosity }, 'plant').kwhPerBbl : 0;
  const data = useMemo(() => trend.filter((t) => t.tH >= -3).map((t) => ({ time: t.time, load: t.rodLoad, pred: t.rodLoadPred, spm: t.spm, oil: t.oil })), [trend]);
  const decisionTime = snap ? trend.find((t) => t.tH >= snap.h)?.time : undefined;
  const markers = decisionTime ? [{ x: decisionTime, label: decision === 'APPROVED' ? (decidedBy === 'AUTOMATION' ? 'auto-executed' : 'executed') : decision === 'ROLLED_BACK' ? 'rolled back' : 'rejected' }] : [];

  return (
    <div className="p-4">
      <PageTitle
        title={`Outcome — ${wellId}`}
        sub={
          <>
            <b>DEMONSTRATION SIMULATION RESULTS</b> — observed values are generated by a simulated plant whose parameters intentionally differ from the prediction model. Not field results.
          </>
        }
        right={o && <Badge tone={o.decision === 'APPROVED' ? 'ok' : 'crit'} className="text-[12px]">{o.decision === 'APPROVED' ? (o.decidedBy === 'AUTOMATION' ? 'AUTO-EXECUTED · SUPERVISED' : 'OPERATOR EXECUTED') : o.decision === 'ROLLED_BACK' ? 'OPERATOR ROLLED BACK' : 'OPERATOR REJECTED'}</Badge>}
      />
      {!o ? (
        <Note>
          {decision
            ? 'Decision recorded — simulating the +24 h response. The outcome appears when the scenario reaches phase 15.'
            : status === 'AWAITING'
              ? 'Awaiting operator decision on the Safety page. The outcome is evaluated after approval (or rejection).'
              : 'No outcome yet. Run the demo scenario and approve (or reject) the recommendation.'}
        </Note>
      ) : (
        <>
          <StatStrip cols={6}>
            <Stat label="SPM" value={`${o.before.spm.toFixed(0)} → ${o.appliedSpm.toFixed(0)}`} unit="spm" />
            <Stat label="Rod load (+24 h)" value={`${o.noAction.rodLoad.toFixed(0)} → ${o.observedAfter.rodLoad.toFixed(0)}`} unit="%" tone={o.observedAfter.rodLoad < 80 ? 'ok' : 'crit'} sub="no-action forecast → simulated observed" />
            <Stat label="Production" value={`${o.before.oil.toFixed(1)} → ${o.observedAfter.oil.toFixed(1)}`} unit="BOPD" sub={`vs ${o.noAction.oil.toFixed(1)} BOPD if no action`} />
            <Stat label="Energy per barrel" value={`${eBefore.toFixed(1)} → ${eAfter.toFixed(1)}`} unit="kWh/bbl" tone={eAfter < eBefore ? 'ok' : undefined} sub={`${(((eBefore - eAfter) / eBefore) * 100).toFixed(0)}% less energy per barrel`} />
            <Stat label="Prediction error (rod load)" value={o.errors.rodLoad.toFixed(1)} unit="%" tone={o.errors.rodLoad < 5 ? 'ok' : 'warn'} prov="SIMULATED" />
            <Stat label="Failure-risk band" value={o.observedAfter.risk} sub={`was ${o.noAction.risk} (no-action forecast)`} tone={o.observedAfter.risk === 'HIGH' || o.observedAfter.risk === 'CRITICAL' ? 'crit' : 'ok'} />
          </StatStrip>
          <div className="mt-3 grid grid-cols-1 gap-3 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)]">
            <Panel title="Before vs after" bodyClass="">
              <BeforeAfter o={o} />
            </Panel>
            <div className="flex flex-col gap-3">
              <Panel title="Predicted vs simulated observation" right={<Prov kind="SIMULATED" label="Demonstration" />}>
                <PredictionValidation o={o} />
                <div className="border-t border-line px-3 py-2 text-[11.5px] text-ink-2">
                  Predicted rod load <b className="num">{o.predictedAfter.rodLoad.toFixed(0)}%</b> · simulated observed <b className="num">{o.observedAfter.rodLoad.toFixed(0)}%</b> · error <b className="num">{o.errors.rodLoad.toFixed(1)}%</b>. The residual is logged to the trust ledger and would be used to retrain the ML residual term.
                </div>
              </Panel>
              <Link to={`/well/${wellId}/history`} className="btn justify-center">
                VIEW MODEL TRUST / HISTORY <ArrowRight size={13} />
              </Link>
            </div>
          </div>
        </>
      )}
      {data.length > 4 && (
        <div className="mt-3 grid grid-cols-1 gap-3 xl:grid-cols-2">
          <Panel title="Rod load through the scenario (%)" right={<Prov kind="SIMULATED" />} bodyClass="px-1 pt-1">
            <TimeSeriesChart
              data={data}
              unit="%"
              domain={[60, 95]}
              markers={markers}
              refLines={[{ y: SAFETY_LIMITS.maxRodLoad, label: 'limit 90%', color: '#b3261e' }]}
              series={[
                { key: 'load', name: 'Observed (sim.)', color: SERIES.s1 },
                { key: 'pred', name: 'Forecast +24 h', color: SERIES.s2, dashed: true },
              ]}
              height={190}
            />
          </Panel>
          <Panel title="Pumping speed through the scenario (strokes/min)" right={<Prov kind="SIMULATED" />} bodyClass="px-1 pt-1">
            <TimeSeriesChart data={data} unit="spm" domain={[4, 12]} markers={markers} series={[{ key: 'spm', name: 'SPM', color: SERIES.s1 }]} height={190} />
          </Panel>
        </div>
      )}
    </div>
  );
}
